/******************************************************************************************************************
Desarrollado por: Avanxo Colombia
Autor: Sergio Andres Ortiz
Proyecto: Global Seguros
Descripción: Clase que implementa la lógica de negocio para realizar las siguientes operaciones
- Probar la clase CRUDGlobal_cls y verificar que cada uno de sus métodos cumpla efectivamente su tarea.

Cambios (Versiones)
-------------------------------------------------------------------------------------------------------
No. Fecha 			Autor 				Descripción
-------------------------------------------------------------------------------------------------------
1.0 16/05/2014 	Sergio Andres Ortiz 	Creación de la clase.

*******************************************************************************************************************/

@isTest
public class CRUDGlobal_tst {

    public static testMethod void myUnitTest() {

    	RecibirInfoCotizadorWS_tst.infoCotizador_test();

    }
}